# Generated by Django 5.0.1 on 2024-01-29 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='modification_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
