# Generated by Django 5.0.1 on 2024-01-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_modification_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['creation_date', 'modification_date', 'title']},
        ),
    ]
